apiVersion: v1
kind: Service
metadata:
  name: friday-prod-service
  labels:
    app: friday-prod
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.109
  externalIPs:
  - 10.24.24.109
  ports:
  - name: http
    port: 80 #local out port
    protocol: TCP
    targetPort: 80 # container port
  selector:
    app: friday-prod #find all pod with app name
  sessionAffinity: None
